import { prisma } from '../../config/database.js'

export async function generateHandoff(ideaId: string, userId: string): Promise<string> {
  const idea = await prisma.idea.findFirst({
    where: { id: ideaId, userId },
    include: {
      attachments: true,
      diagrams: true,
      questions: { orderBy: { ordering: 'asc' } },
    },
  })

  if (!idea) throw new Error('Idea no encontrada')

  const mergedAnalysis = idea.mergedResponse || idea.claudeResponse || idea.gptResponse || ''

  let handoff = `# Cursor Handoff — ${idea.title}

**Mode:** ${idea.recommendation === 'agent' ? 'Agent' : 'Plan'}
**Change Type:** ${idea.mode === 'complex' ? 'Big/Complex Change' : 'Simple Change'}

---

## Original Description
${idea.description}
`

  if (idea.mode === 'complex') {
    if (idea.projectContext) {
      handoff += `\n## Project Context\n${idea.projectContext}\n`
    }
    if (idea.affectedAreas) {
      handoff += `\n## Affected Areas\n${idea.affectedAreas}\n`
    }
    if (idea.structuralNotes) {
      handoff += `\n## Structural Notes\n${idea.structuralNotes}\n`
    }
  }

  if (idea.questions.length > 0) {
    const answered = idea.questions.filter(q => q.answer)
    if (answered.length > 0) {
      handoff += '\n## Clarifications\n'
      for (const q of answered) {
        handoff += `- **Q:** ${q.question}\n  **A:** ${q.answer}\n`
      }
    }
  }

  if (mergedAnalysis) {
    handoff += `\n## AI Analysis (merged from Claude + GPT)\n${mergedAnalysis}\n`
  }

  if (idea.attachments.length > 0) {
    handoff += '\n## Attached Files\n'
    for (const a of idea.attachments) {
      handoff += `- ${a.originalName} (${a.mimeType}, ${formatBytes(a.sizeBytes)})\n`
    }
  }

  if (idea.diagrams.length > 0) {
    handoff += `\n## Diagrams\n${idea.diagrams.length} diagram(s) attached. Review them for visual context.\n`
  }

  if (idea.recommendReason) {
    handoff += `\n## Mode Recommendation\n${idea.recommendReason}\n`
  }

  handoff += `\n---\n*Generated by Cubo AI Idea Description Generator*\n`

  await prisma.idea.update({
    where: { id: ideaId },
    data: { handoffText: handoff, status: 'done' },
  })

  return handoff
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
